-- Insert Default Admin (Password: admin123)
-- The hash below is generated by BCrypt for 'admin123'
INSERT INTO users (mobile, password, full_name, role, wallet_balance, total_earned, referral_code, active, created_at)
SELECT '9999999999', '$2a$10$N.zmdr9k7uOCQb376ye.5O/6lqOV.i2d/gQ5i.c5uD.s5uD.s5u', 'Super Admin', 'ROLE_ADMIN', 0.0, 0.0, 'ADMIN001', true, NOW()
WHERE NOT EXISTS (SELECT 1 FROM users WHERE mobile = '9999999999');

-- Insert Sample Tasks
INSERT INTO tasks (title, description, reward_amount, image_url, action_url, active, created_at)
SELECT 'Watch Video', 'Watch this 30 sec video', 10.0, 'default.png', 'https://youtube.com', true, NOW()
WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE title = 'Watch Video');